export const moviesData = [
  {
    id: "shawshank",
    title: "The Shawshank Redemption",
    moods: ["uplifting", "thoughtful", "chill"],
    genres: ["drama"],
    hasGif: true,
    poster: "assets/shawshank.jpg",
    trailerGif: "assets/shawshank.gif",
  },
  {
    id: "inception",
    title: "Inception",
    moods: ["thriller", "dark"],
    genres: ["sci-fi", "action", "thriller"],
    hasGif: true,
    poster: "assets/inception.jpg",
    trailerGif: "assets/inception.gif",
  },
  {
    id: "dark_knight",
    title: "The Dark Knight",
    moods: ["thriller", "dark"],
    genres: ["action", "thriller"],
    hasGif: false,
    poster: "assets/dark_knight.jpg",
    trailerGif: "",
  },
  {
    id: "la_la_land",
    title: "La La Land",
    moods: ["romance", "uplifting", "chill"],
    genres: ["romance", "drama"],
    hasGif: true,
    poster: "assets/la_la_land.jpg",
    trailerGif: "assets/la_la_land.gif",
  },
  {
    id: "interstellar",
    title: "Interstellar",
    moods: ["thoughtful", "uplifting"],
    genres: ["sci-fi", "drama"],
    hasGif: true,
    poster: "assets/interstellar.jpg",
    trailerGif: "assets/interstellar.gif",
  },
  {
    id: "parasite",
    title: "Parasite",
    moods: ["thriller", "dark"],
    genres: ["thriller", "drama"],
    hasGif: true,
    poster: "assets/parasite.jpg",
    trailerGif: "assets/parasite.gif",
  },
  {
    id: "spirited_away",
    title: "Spirited Away",
    moods: ["chill", "uplifting"],
    genres: ["animation", "fantasy"],
    hasGif: false,
    poster: "assets/spirited_away.jpg",
    trailerGif: "",
  },
  {
    id: "mad_max_fury_road",
    title: "Mad Max: Fury Road",
    moods: ["thriller"],
    genres: ["action", "thriller"],
    hasGif: true,
    poster: "assets/mad_max_fury_road.jpg",
    trailerGif: "assets/mad_max_fury_road.gif",
  },
  {
    id: "before_sunrise",
    title: "Before Sunrise",
    moods: ["romance", "chill"],
    genres: ["romance", "drama"],
    hasGif: false,
    poster: "assets/before_sunrise.jpg",
    trailerGif: "",
  },
  {
    id: "arrival",
    title: "Arrival",
    moods: ["thoughtful", "dark"],
    genres: ["sci-fi", "drama"],
    hasGif: true,
    poster: "assets/arrival.jpg",
    trailerGif: "assets/arrival.gif",
  },
];

// Use these to render filters dynamically
export const moodsEx = [
  "chill",
  "funny",
  "dark",
  "uplifting",
  "thriller",
  "romance",
  "thoughtful",
];
export const genresEx = [
  "drama",
  "comedy",
  "action",
  "thriller",
  "sci-fi",
  "romance",
  "animation",
  "fantasy",
];
